# Generated by Django 5.1.3 on 2024-12-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='links',
        ),
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.TextField(default='', help_text='Link'),
            preserve_default=False,
        ),
    ]
